Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\RobloxStudioBeta.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\RobloxPlayerBeta.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\WAR.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\X-Plane.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\X-Plane-32bit.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Tidalis.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SublevelZero.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\sspace.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Pandora.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Overture.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\oolite.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\NEOScavenger.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Gnomoria.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Audiosurf2.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Application-x64.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\AIWar.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\FlagAC4BFSP.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Tales of Zestiria.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\UE4-Win64-Test.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\THUG.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Minecraft.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\EDLaunch.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\TmUnitedForever.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Ziggurat.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Zigfrak.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\yso_win.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\isaac-ng.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\XRebirth.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\X3TC.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\X3AP_n.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\X3AP.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\WorldOfGoo.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\WL2.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Windward.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Wildstar.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\WorldOfTanks.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\WorldOfTanks_eu.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Waves.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\v2game.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\uplink.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\UNDERTALE.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Trine2_32bit.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Trine.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Torchlight2.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\TombRaider.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Timberman.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\They Bleed Pixels PC.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Terraria.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SuperMeatBoy.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\superhexagon.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Sunless Sea.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\starwarsbattlefront.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\StarDrive.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SpaceChem.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\sots2.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SkullGirls.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Sins of a Solar Empire Rebellion.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\ShooterGame.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Shogun2.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\shatteredplanet.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\sh4.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Se4.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Scribble.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SanctumGame-Win32-Shipping.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Rome2.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Reus.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\reprisaluniverse.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\RebelGalaxySteam.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\RebelGalaxyGOG.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\ReassemblyRelease.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Really Big Sky.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\ProjectZomboid.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Prison Architect.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Polynomial.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\PlanetSide2_x64.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\payday2_win32_release.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\payday2_win64_release.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\PAC-MAN.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\nuclearthrone.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\MKKE.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\MetroLL.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\KSP.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Kingdom.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\HotlineMiami.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\HotlineGL.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Hexcells.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Hexcells Plus.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\GeometryWars.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\GalCiv2.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\FTLGame.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\eu4.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\EndlessLegend.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\ed6_win.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\DXHRDC.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Dwarf Fortress.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\DustAET.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\DungeonoftheEndless.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\DragonAgeInquisition.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\DotP_D14.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\dontstarve.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\DMC-DevilMayCry.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\defcon.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Darksiders2.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Darkest.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Cities.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Brothers.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Borderlands2.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Borderlands3.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Borderlands.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\BloodBowl2_GL_32.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\BloodBowl2_DX_32.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\BloodBowl2.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Bastion.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Atilla.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\dfbhd.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Scrivener.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Star_Trek_Online.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\vermintide.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\RebelGalaxyGOG.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\RebelGalaxy.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\downwell.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\hng.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\HeroesAndGeneralsDesktop.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\broforce_beta.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\maniaplanet.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\arma3.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\ArmA2OA.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\arma2.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\aces.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Unturned.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\toribash.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Tabletop Simulator.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\starbound_opengl.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\starbound.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SpeedRunners.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\sir.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\quakelive_steam.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\PathOfExileSteam.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Not the Robots.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\WizardWarsLauncher.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\kofxiii.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Hero_Siege.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Hammerwatch.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Guac.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\FullMojo.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\final_exam.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\eurotrucks2.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\DungeonSouls.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\dontstarve_steam.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Disco Dodgeball.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\dirt3_game.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\castle.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\battlevschess.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\One Finger Death Punch.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\TOXIKK.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\ktane.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\FortniteClient-Win64-Shipping.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\csgo.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Dofus.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\ACValhalla.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\factorio.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Hades.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\InfraSpace.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Mindustry.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\oriDE.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\FactoryGame.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Settlement Survival.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Gta5.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Dishonored2.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\RocketLeague.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\BloonsTD6.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\valheim.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\ScrapMechanic.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\KSP_x64.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\CosmicShake.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\AnomalyLauncher.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\AnomalyDX11.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\VRising.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SonsOfTheForest.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Borderlands3.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Rise of Industry.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\PathOfExile.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\PathOfExile_x64.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Ryujinx.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\yuzu-room.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\yuzu-cmd.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\yuzu.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\QtWebEngineProcess.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Ryujinx.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\PAYDAY3-Win64-Shipping.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000003" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\waterfox.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\firefox.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\chrome.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\opera.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\steam.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\steamwebhelper.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\rare.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\MicrosoftEdgeUpdate.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Edge.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\EmptyStandbyList.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\ESL.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\EpicGamesLauncher.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Spotify.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\BakkesMod.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\EpicOnlineServices.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\EpicOnlineServicesHost.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\EpicWebHelper.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Vlc.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Update.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Discord.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\simplewall.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\wallpaper32.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\updater.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\7zFM.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\7z.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Authy Desktop.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Optimizer.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Services.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\RLBotGUIX.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\StartAllBackCfg.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\UpdateCheck.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\streamlink.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\streamlinkw.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\streamlink-twitch-gui.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Cheat Engine.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\cheatengine-i386.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\cheatengine-x86_64.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\cheatengine-x86_64-SSE4-AVX2.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\TEST.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\StartUP.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\WinMemoryCleaner.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\AdguardPortable.tmp\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\AdguardPortable.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\AdguardSvc.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\AdguardPortable.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Adguard.BrowserExtensionHost.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Adguard.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Adguard.Tools.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\certutil.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\maintenancetool.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SteelSeriesGG.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SteelSeriesUpdateService.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SteelSeriesGGClient.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SSHZExecutor.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SSOverlay.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SteelSeriesEngine.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\win_driver_installer.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\computerhardwareids.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\explorer.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\spoolsv.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\spaceman.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\spaceutil.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Spectrum.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\sort.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SpaceAgent.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\slui.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\dwm.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\audiodg.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Taskmgr.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\ntprint.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\csrss.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\ctfmon.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\svchost.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\WmiPrvSE.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\RuntimeBroker.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\dllhost.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\sppsvc.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\wallpaperservice32_c.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\ui32.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SetTimerResolutionService.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\vmms.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\lsass.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Magnify.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\lusrmgr.msc\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\manage-bde.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\winlogon.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\manage-bde.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\winload.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\wininit.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\WindowsUpdateElevatedInstaller.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\smss.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\sihost.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\MicrosoftEdgeUpdate.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\ntoskrnl.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\manage-bde.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\services.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\lghub_updater.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\lghub_uninstaller.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\lghub_agent.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\lghub.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\logi_crashpad_handler.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\lghub_system_tray.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\librewolf.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\CompatTelRunner.exe" /v "Debugger" /t REG_SZ /d "%windir%\System32\taskkill.exe" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\AggregatorHost.exe" /v "Debugger" /t REG_SZ /d "%windir%\System32\taskkill.exe" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\DeviceCensus.exe" /v "Debugger" /t REG_SZ /d "%windir%\System32\taskkill.exe" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\FeatureLoader.exe" /v "Debugger" /t REG_SZ /d "%windir%\System32\taskkill.exe" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\BingChatInstaller.exe" /v "Debugger" /t REG_SZ /d "%windir%\System32\taskkill.exe" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\BGAUpsell.exe" /v "Debugger" /t REG_SZ /d "%windir%\System32\taskkill.exe" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\BCILauncher.exe" /v "Debugger" /t REG_SZ /d "%windir%\System32\taskkill.exe" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SearchIndexer.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000005" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\ctfmon.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000005" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\fontdrvhost.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\fontdrvhost.exe\PerfOptions" /v "IoPriority" /t REG_DWORD /d "00000000" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\lsass.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\sihost.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\sihost.exe\PerfOptions" /v "IoPriority" /t REG_DWORD /d "00000000" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\sppsvc.exe\PerfOptions" /v "CpuPriorityClass" /t REG_DWORD /d "00000001" /f >nul 2>&1
Reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\sppsvc.exe\PerfOptions" /v "IoPriority" /t REG_DWORD /d "00000000" /f >nul 2>&1